openapi: 3.0.0
info:
  title: 'Article API'
  description: 'This Documentation is for the Article API endpoints'
  contact:
    email: tesleemolamilekan902@gmail.com
  license:
    name: 'Apache 2.0'
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: true
paths:
  /api/articles:
    get:
      tags:
        - Article
      summary: 'Finds Pets by status'
      description: 'Multiple status values can be provided with comma separated string'
      operationId: index
      parameters:
        -
          name: status
          in: query
          description: 'Status values that needed to be considered for filter'
          required: true
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'Invalid status value'
